# Generated by Django 5.1.1 on 2024-10-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galeria/')),
            ],
        ),
        migrations.AlterField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platillos/'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='ruta',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
    ]
