# Generated by Django 5.1.7 on 2025-03-17 22:32

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_galeria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=gestion.models.upload_to_platillos),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='ruta',
            field=models.ImageField(blank=True, null=True, upload_to=gestion.models.upload_to_promotions),
        ),
    ]
